INSERT INTO `COREAPP`.`MODULES` (`NAME`, `STATUS`, `FOLDER`, `URL`, `GUIFLAG`, `CREATEDBY`, `CREATEDAT`, `MODIFIEDBY`, `MODIFIEDAT`, `RANK`)
VALUES
('Reference Library', 1, 'referencelibrary', 'referencelibrary', 1, 'system', '0000-00-00 00:00:00', 'system', '0000-00-00 00:00:00', 0);


CREATE TABLE ATTACHMENT.MIGRATIONS
(
  MIGRATIONID INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(255) NOT NULL,
  MIGRATEDAT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE UNIQUE INDEX AKMIGRATIONS01 ON ATTACHMENT.MIGRATIONS(NAME);
