--
-- Introduce referenceLibraryHeader table.
--

CREATE TABLE ATTACHMENT.REFERENCELIBRARYHEADER 
(
	REFLIBHEADERID       BIGINT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRIPTION           VARCHAR(255),
	DOCTYPEID     INT,
    STARTDATETIME     DATETIME,
    ENDDATETIME     DATETIME,
    DOCPRIORITYID     INT,
	CREATEDBY      VARCHAR(100),
	CREATEDAT      DATETIME,
	MODIFIEDBY     VARCHAR(100),
	MODIFIEDAT     DATETIME
) ENGINE = INNODB;





