USE COREAPP;

-- create REFERENCELIBRARY top-level code if it doesn't exist
INSERT INTO CODES (NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT 'REFERENCELIBRARY','','Reference Library module-specific codes','1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID is null AND NAME='REFERENCELIBRARY');

SELECT @referencelibrary:=CODEID as CODEID from CODES where PARENTCODEID is null AND NAME='REFERENCELIBRARY';

-- create REFERENCELIBRARY.LIBRARY
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @referencelibrary,'LIBRARY','','Codes related to LIBRARY','1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@referencelibrary AND NAME='LIBRARY');

SELECT @library:=CODEID as CODEID from CODES where PARENTCODEID=@referencelibrary AND NAME='LIBRARY';



-- create REFERENCELIBRARY.LIBRARY.DOCTYPES
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @library,'DOCTYPES','','Doctypes of Reference Library','1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@library AND NAME='DOCTYPES');

SELECT @doctypes:=CODEID as CODEID from CODES where PARENTCODEID=@library AND NAME='DOCTYPES';

-- create REFERENCELIBRARY.LIBRARY.DOCPRIORITYTYPES
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @library,'DOCPRIORITYTYPES','','Docprioritytypes of Reference Library','1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@library AND NAME='DOCPRIORITYTYPES');

SELECT @docprioritytypes:=CODEID as CODEID from CODES where PARENTCODEID=@library AND NAME='DOCPRIORITYTYPES';
--
-- POPULATE 
--

set @name:='PUBLIC';
set @description:='Public';
set @value:='1';
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @doctypes,@name,@value,@description,'1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@doctypes AND (VALUE COLLATE utf8_general_ci)=@value);

set @name:='INDIVIDUAL';
set @description:='Individual';
set @value:='2';
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @doctypes,@name,@value,@description,'1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@doctypes AND (VALUE COLLATE utf8_general_ci)=@value);


set @name:='HOTLIST';
set @description:='Hotlist';
set @value:='1';
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @doctypes,@name,@value,@description,'1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@docprioritytypes AND (VALUE COLLATE utf8_general_ci)=@value);

set @name:='NORMAL';
set @description:='Normal';
set @value:='2';
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @doctypes,@name,@value,@description,'1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@docprioritytypes AND (VALUE COLLATE utf8_general_ci)=@value);

set @name:='PRIVATE';
set @description:='Private';
set @value:='3';
INSERT INTO CODES (PARENTCODEID,NAME,VALUE,DESCRIPTION,ACTIVEFLAG,CREATEDAT,CREATEDBY,UPDATEDAT,UPDATEDBY)
SELECT @doctypes,@name,@value,@description,'1',NOW(),'system',NOW(),'system'
FROM DUAL WHERE NOT EXISTS (SELECT * FROM CODES WHERE PARENTCODEID=@docprioritytypes AND (VALUE COLLATE utf8_general_ci)=@value);



